// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Panda.NuGet.AsanaClient.Clients.Rule_triggers.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Rule_triggers
{
    /// <summary>
    /// Builds and executes requests for operations under \rule_triggers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Rule_triggersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Panda.NuGet.AsanaClient.Clients.rule_triggers.item collection</summary>
        /// <param name="position">The ID of the incoming web request trigger. This value is a path parameter that is automatically generated for the API endpoint.</param>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Rule_triggers.Item.WithRule_trigger_gItemRequestBuilder"/></returns>
        public global::Panda.NuGet.AsanaClient.Clients.Rule_triggers.Item.WithRule_trigger_gItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("rule_trigger_gid", position);
                return new global::Panda.NuGet.AsanaClient.Clients.Rule_triggers.Item.WithRule_trigger_gItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Rule_triggers.Rule_triggersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Rule_triggersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rule_triggers", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Rule_triggers.Rule_triggersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Rule_triggersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rule_triggers", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
