// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Tasks.Item.Time_tracking_entries
{
    /// <summary>*Optional*. The current approval status of the entry.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Time_tracking_entriesPostResponse_data_approval_status
    {
        [EnumMember(Value = "DRAFT")]
        #pragma warning disable CS1591
        DRAFT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBMITTED")]
        #pragma warning disable CS1591
        SUBMITTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPROVED")]
        #pragma warning disable CS1591
        APPROVED,
        #pragma warning restore CS1591
        [EnumMember(Value = "REJECTED")]
        #pragma warning disable CS1591
        REJECTED,
        #pragma warning restore CS1591
    }
}
