// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Panda.NuGet.AsanaClient.Clients.Tasks.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Tasks
{
    /// <summary>
    /// Builds and executes requests for operations under \tasks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TasksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Panda.NuGet.AsanaClient.Clients.tasks.item collection</summary>
        /// <param name="position">The task to operate on.</param>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.WithTask_gItemRequestBuilder"/></returns>
        public global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.WithTask_gItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("task_gid", position);
                return new global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.WithTask_gItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TasksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tasks{?assignee*,completed_since*,limit*,modified_since*,offset*,opt_fields,opt_pretty*,project*,section*,workspace*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TasksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tasks{?assignee*,completed_since*,limit*,modified_since*,offset*,opt_fields,opt_pretty*,project*,section*,workspace*}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:read&lt;/code&gt;Returns the compact task records for some filtered set of tasks. Use one or more of the parameters provided to filter the tasks returned. You must specify a `project` or `tag` if you do not specify `assignee` and `workspace`.For more complex task retrieval, use [workspaces/{workspace_gid}/tasks/search](/reference/searchtasksforworkspace).
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksGetResponse?> GetAsTasksGetResponseAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder.TasksRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksGetResponse> GetAsTasksGetResponseAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder.TasksRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksGetResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:read&lt;/code&gt;Returns the compact task records for some filtered set of tasks. Use one or more of the parameters provided to filter the tasks returned. You must specify a `project` or `tag` if you do not specify `assignee` and `workspace`.For more complex task retrieval, use [workspaces/{workspace_gid}/tasks/search](/reference/searchtasksforworkspace).
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsTasksGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksResponse?> GetAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder.TasksRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksResponse> GetAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder.TasksRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Creating a new task is as easy as POSTing to the `/tasks` endpoint with adata block containing the fields you’d like to set on the task. Anyunspecified fields will take on default values.Every task is required to be created in a specific workspace, and thisworkspace cannot be changed once set. The workspace need not be setexplicitly if you specify `projects` or a `parent` task instead.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksPostResponse?> PostAsTasksPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder.TasksRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksPostResponse> PostAsTasksPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder.TasksRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksPostResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Creating a new task is as easy as POSTing to the `/tasks` endpoint with adata block containing the fields you’d like to set on the task. Anyunspecified fields will take on default values.Every task is required to be created in a specific workspace, and thisworkspace cannot be changed once set. The workspace need not be setexplicitly if you specify `projects` or a `parent` task instead.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsTasksPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksResponse?> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder.TasksRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksResponse> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder.TasksRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Tasks.Tasks500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:read&lt;/code&gt;Returns the compact task records for some filtered set of tasks. Use one or more of the parameters provided to filter the tasks returned. You must specify a `project` or `tag` if you do not specify `assignee` and `workspace`.For more complex task retrieval, use [workspaces/{workspace_gid}/tasks/search](/reference/searchtasksforworkspace).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder.TasksRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder.TasksRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Creating a new task is as easy as POSTing to the `/tasks` endpoint with adata block containing the fields you’d like to set on the task. Anyunspecified fields will take on default values.Every task is required to be created in a specific workspace, and thisworkspace cannot be changed once set. The workspace need not be setexplicitly if you specify `projects` or a `parent` task instead.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder.TasksRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder.TasksRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:read&lt;/code&gt;Returns the compact task records for some filtered set of tasks. Use one or more of the parameters provided to filter the tasks returned. You must specify a `project` or `tag` if you do not specify `assignee` and `workspace`.For more complex task retrieval, use [workspaces/{workspace_gid}/tasks/search](/reference/searchtasksforworkspace).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TasksRequestBuilderGetQueryParameters 
        {
            /// <summary>The assignee to filter tasks on. If searching for unassigned tasks, assignee.any = null can be specified.*Note: If you specify `assignee`, you must also specify the `workspace` to filter on.*</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("assignee")]
            public string? Assignee { get; set; }
#nullable restore
#else
            [QueryParameter("assignee")]
            public string Assignee { get; set; }
#endif
            /// <summary>Only return tasks that are either incomplete or that have been completed since this time.</summary>
            [QueryParameter("completed_since")]
            public DateTimeOffset? CompletedSince { get; set; }
            /// <summary>Results per page.The number of objects to return per page. The value must be between 1 and 100.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Only return tasks that have been modified since the given time.*Note: A task is considered “modified” if any of its propertieschange, or associations between it and other objects are modified(e.g.  a task being added to a project). A task is not consideredmodified just because another object it is associated with (e.g. asubtask) is modified. Actions that count as modifying the taskinclude assigning, renaming, completing, and adding stories.*</summary>
            [QueryParameter("modified_since")]
            public DateTimeOffset? ModifiedSince { get; set; }
            /// <summary>Offset token.An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results.*Note: You can only pass in an offset that was returned to you via a previously paginated request.*</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("offset")]
            public string? Offset { get; set; }
#nullable restore
#else
            [QueryParameter("offset")]
            public string Offset { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
            [Obsolete("This property is deprecated, use OptFieldsAsGetOptFieldsQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public string[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public string[] OptFields { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Tasks.GetOpt_fieldsQueryParameterType[]? OptFieldsAsGetOptFieldsQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Tasks.GetOpt_fieldsQueryParameterType[] OptFieldsAsGetOptFieldsQueryParameterType { get; set; }
#endif
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
            /// <summary>The project to filter tasks on.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("project")]
            public string? Project { get; set; }
#nullable restore
#else
            [QueryParameter("project")]
            public string Project { get; set; }
#endif
            /// <summary>The section to filter tasks on.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("section")]
            public string? Section { get; set; }
#nullable restore
#else
            [QueryParameter("section")]
            public string Section { get; set; }
#endif
            /// <summary>The workspace to filter tasks on.*Note: If you specify `workspace`, you must also specify the `assignee` to filter on.*</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("workspace")]
            public string? Workspace { get; set; }
#nullable restore
#else
            [QueryParameter("workspace")]
            public string Workspace { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TasksRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder.TasksRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Creating a new task is as easy as POSTing to the `/tasks` endpoint with adata block containing the fields you’d like to set on the task. Anyunspecified fields will take on default values.Every task is required to be created in a specific workspace, and thisworkspace cannot be changed once set. The workspace need not be setexplicitly if you specify `projects` or a `parent` task instead.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TasksRequestBuilderPostQueryParameters 
        {
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
            [Obsolete("This property is deprecated, use OptFieldsAsPostOptFieldsQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public string[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public string[] OptFields { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Tasks.PostOpt_fieldsQueryParameterType[]? OptFieldsAsPostOptFieldsQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Tasks.PostOpt_fieldsQueryParameterType[] OptFieldsAsPostOptFieldsQueryParameterType { get; set; }
#endif
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TasksRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder.TasksRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
