// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents
{
    /// <summary>
    /// Builds and executes requests for operations under \tasks\{task_gid}\removeDependents
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RemoveDependentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RemoveDependentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tasks/{task_gid}/removeDependents{?opt_pretty*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RemoveDependentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tasks/{task_gid}/removeDependents{?opt_pretty*}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Unlinks a set of dependents from this task.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsPostResponse?> PostAsRemoveDependentsPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsRequestBuilder.RemoveDependentsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsPostResponse> PostAsRemoveDependentsPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsRequestBuilder.RemoveDependentsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents401Error.CreateFromDiscriminatorValue },
                { "402", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents402Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsPostResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Unlinks a set of dependents from this task.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsRemoveDependentsPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsResponse?> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsRequestBuilder.RemoveDependentsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsResponse> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsRequestBuilder.RemoveDependentsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents401Error.CreateFromDiscriminatorValue },
                { "402", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents402Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependents500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Unlinks a set of dependents from this task.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsRequestBuilder.RemoveDependentsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsRequestBuilder.RemoveDependentsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Unlinks a set of dependents from this task.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RemoveDependentsRequestBuilderPostQueryParameters 
        {
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RemoveDependentsRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveDependents.RemoveDependentsRequestBuilder.RemoveDependentsRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
