// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject
{
    /// <summary>
    /// Builds and executes requests for operations under \tasks\{task_gid}\addProject
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AddProjectRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AddProjectRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tasks/{task_gid}/addProject{?opt_pretty*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AddProjectRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tasks/{task_gid}/addProject{?opt_pretty*}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Adds the task to the specified project, in the optional locationspecified. If no location arguments are given, the task will be added tothe end of the project.`addProject` can also be used to reorder a task within a project orsection that already contains it.**Positioning the task:**- Use `insert_before` or `insert_after` with a task ID to position relative to another task- Use `section` alone to add the task to the end of a section- Use `section` with `insert_after: null` to add to the **beginning** of a section- Use `section` with `insert_before: null` to add to the **end** of a section- Use `section` with `insert_before` or `insert_after` (non-null) to position relative to a task within that section. The anchor task must be in the specified section.At most one of `insert_before` or `insert_after` should be specified (both cannot be used together).A task can have at most 20 projects multi-homed to it.Returns an empty data block.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectPostResponse?> PostAsAddProjectPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectRequestBuilder.AddProjectRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectPostResponse> PostAsAddProjectPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectRequestBuilder.AddProjectRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectPostResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Adds the task to the specified project, in the optional locationspecified. If no location arguments are given, the task will be added tothe end of the project.`addProject` can also be used to reorder a task within a project orsection that already contains it.**Positioning the task:**- Use `insert_before` or `insert_after` with a task ID to position relative to another task- Use `section` alone to add the task to the end of a section- Use `section` with `insert_after: null` to add to the **beginning** of a section- Use `section` with `insert_before: null` to add to the **end** of a section- Use `section` with `insert_before` or `insert_after` (non-null) to position relative to a task within that section. The anchor task must be in the specified section.At most one of `insert_before` or `insert_after` should be specified (both cannot be used together).A task can have at most 20 projects multi-homed to it.Returns an empty data block.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsAddProjectPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectResponse?> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectRequestBuilder.AddProjectRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectResponse> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectRequestBuilder.AddProjectRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProject500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Adds the task to the specified project, in the optional locationspecified. If no location arguments are given, the task will be added tothe end of the project.`addProject` can also be used to reorder a task within a project orsection that already contains it.**Positioning the task:**- Use `insert_before` or `insert_after` with a task ID to position relative to another task- Use `section` alone to add the task to the end of a section- Use `section` with `insert_after: null` to add to the **beginning** of a section- Use `section` with `insert_before: null` to add to the **end** of a section- Use `section` with `insert_before` or `insert_after` (non-null) to position relative to a task within that section. The anchor task must be in the specified section.At most one of `insert_before` or `insert_after` should be specified (both cannot be used together).A task can have at most 20 projects multi-homed to it.Returns an empty data block.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectRequestBuilder.AddProjectRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectRequestBuilder.AddProjectRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Adds the task to the specified project, in the optional locationspecified. If no location arguments are given, the task will be added tothe end of the project.`addProject` can also be used to reorder a task within a project orsection that already contains it.**Positioning the task:**- Use `insert_before` or `insert_after` with a task ID to position relative to another task- Use `section` alone to add the task to the end of a section- Use `section` with `insert_after: null` to add to the **beginning** of a section- Use `section` with `insert_before: null` to add to the **end** of a section- Use `section` with `insert_before` or `insert_after` (non-null) to position relative to a task within that section. The anchor task must be in the specified section.At most one of `insert_before` or `insert_after` should be specified (both cannot be used together).A task can have at most 20 projects multi-homed to it.Returns an empty data block.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AddProjectRequestBuilderPostQueryParameters 
        {
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AddProjectRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddProject.AddProjectRequestBuilder.AddProjectRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
