// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Exports.Resource
{
    /// <summary>
    /// A generic Asana Resource, containing a globally unique identifier.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResourcePostResponse_data : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Globally unique identifier of the resource, as a string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Gid { get; private set; }
#nullable restore
#else
        public string Gid { get; private set; }
#endif
        /// <summary>A *resource_export* object represents a request to bulk export objects for one or more resources.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Panda.NuGet.AsanaClient.Clients.Exports.Resource.ResourcePostResponse_data_new_resource_export? NewResourceExport { get; set; }
#nullable restore
#else
        public global::Panda.NuGet.AsanaClient.Clients.Exports.Resource.ResourcePostResponse_data_new_resource_export NewResourceExport { get; set; }
#endif
        /// <summary>A *resource_export* object represents a request to bulk export objects for one or more resources.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceSubtype { get; private set; }
#nullable restore
#else
        public string ResourceSubtype { get; private set; }
#endif
        /// <summary>The base type of this resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceType { get; private set; }
#nullable restore
#else
        public string ResourceType { get; private set; }
#endif
        /// <summary>The current status of this job.</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Exports.Resource.ResourcePostResponse_data_status? Status { get; private set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Exports.Resource.ResourcePostResponse_data"/> and sets the default values.
        /// </summary>
        public ResourcePostResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Exports.Resource.ResourcePostResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Panda.NuGet.AsanaClient.Clients.Exports.Resource.ResourcePostResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Panda.NuGet.AsanaClient.Clients.Exports.Resource.ResourcePostResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "gid", n => { Gid = n.GetStringValue(); } },
                { "new_resource_export", n => { NewResourceExport = n.GetObjectValue<global::Panda.NuGet.AsanaClient.Clients.Exports.Resource.ResourcePostResponse_data_new_resource_export>(global::Panda.NuGet.AsanaClient.Clients.Exports.Resource.ResourcePostResponse_data_new_resource_export.CreateFromDiscriminatorValue); } },
                { "resource_subtype", n => { ResourceSubtype = n.GetStringValue(); } },
                { "resource_type", n => { ResourceType = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Panda.NuGet.AsanaClient.Clients.Exports.Resource.ResourcePostResponse_data_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Panda.NuGet.AsanaClient.Clients.Exports.Resource.ResourcePostResponse_data_new_resource_export>("new_resource_export", NewResourceExport);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
