// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Organization_exports.Item
{
    /// <summary>The current state of the export.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithOrganization_export_gGetResponse_data_state
    {
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "started")]
        #pragma warning disable CS1591
        Started,
        #pragma warning restore CS1591
        [EnumMember(Value = "finished")]
        #pragma warning disable CS1591
        Finished,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
