// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags
{
    /// <summary>
    /// Builds and executes requests for operations under \workspaces\{workspace_gid}\tags
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TagsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TagsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workspaces/{workspace_gid}/tags{?limit*,offset*,opt_fields,opt_pretty*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TagsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workspaces/{workspace_gid}/tags{?limit*,offset*,opt_fields,opt_pretty*}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tags:read&lt;/code&gt;Returns the compact tag records for some filtered set of tags. Use one or more of the parameters provided to filter the tags returned.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsGetResponse?> GetAsTagsGetResponseAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder.TagsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsGetResponse> GetAsTagsGetResponseAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder.TagsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsGetResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tags:read&lt;/code&gt;Returns the compact tag records for some filtered set of tags. Use one or more of the parameters provided to filter the tags returned.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsTagsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsResponse?> GetAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder.TagsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsResponse> GetAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder.TagsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tags:write&lt;/code&gt;Creates a new tag in a workspace or organization.Every tag is required to be created in a specific workspace ororganization, and this cannot be changed once set. Note that you can usethe workspace parameter regardless of whether or not it is anorganization.Returns the full record of the newly created tag.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsPostResponse?> PostAsTagsPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder.TagsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsPostResponse> PostAsTagsPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder.TagsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsPostResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tags:write&lt;/code&gt;Creates a new tag in a workspace or organization.Every tag is required to be created in a specific workspace ororganization, and this cannot be changed once set. Note that you can usethe workspace parameter regardless of whether or not it is anorganization.Returns the full record of the newly created tag.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsTagsPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsResponse?> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder.TagsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsResponse> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder.TagsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.Tags500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tags:read&lt;/code&gt;Returns the compact tag records for some filtered set of tags. Use one or more of the parameters provided to filter the tags returned.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder.TagsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder.TagsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tags:write&lt;/code&gt;Creates a new tag in a workspace or organization.Every tag is required to be created in a specific workspace ororganization, and this cannot be changed once set. Note that you can usethe workspace parameter regardless of whether or not it is anorganization.Returns the full record of the newly created tag.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder.TagsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder.TagsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tags:read&lt;/code&gt;Returns the compact tag records for some filtered set of tags. Use one or more of the parameters provided to filter the tags returned.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TagsRequestBuilderGetQueryParameters 
        {
            /// <summary>Results per page.The number of objects to return per page. The value must be between 1 and 100.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Offset token.An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results.*Note: You can only pass in an offset that was returned to you via a previously paginated request.*</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("offset")]
            public string? Offset { get; set; }
#nullable restore
#else
            [QueryParameter("offset")]
            public string Offset { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
            [Obsolete("This property is deprecated, use OptFieldsAsGetOptFieldsQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public string[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public string[] OptFields { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.GetOpt_fieldsQueryParameterType[]? OptFieldsAsGetOptFieldsQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.GetOpt_fieldsQueryParameterType[] OptFieldsAsGetOptFieldsQueryParameterType { get; set; }
#endif
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TagsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder.TagsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tags:write&lt;/code&gt;Creates a new tag in a workspace or organization.Every tag is required to be created in a specific workspace ororganization, and this cannot be changed once set. Note that you can usethe workspace parameter regardless of whether or not it is anorganization.Returns the full record of the newly created tag.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TagsRequestBuilderPostQueryParameters 
        {
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
            [Obsolete("This property is deprecated, use OptFieldsAsPostOptFieldsQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public string[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public string[] OptFields { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.PostOpt_fieldsQueryParameterType[]? OptFieldsAsPostOptFieldsQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.PostOpt_fieldsQueryParameterType[] OptFieldsAsPostOptFieldsQueryParameterType { get; set; }
#endif
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TagsRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder.TagsRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
