// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Workspace_memberships
{
    [Obsolete("This class is obsolete. Use Workspace_membershipsGetResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Workspace_membershipsResponse : global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Workspace_memberships.Workspace_membershipsGetResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Workspace_memberships.Workspace_membershipsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Workspace_memberships.Workspace_membershipsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Workspace_memberships.Workspace_membershipsResponse();
        }
    }
}
#pragma warning restore CS0618
