// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Project_memberships.Item
{
    /// <summary>Whether the member has full access or comment-only access to the project.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithProject_membership_gGetResponse_data_write_access
    {
        [EnumMember(Value = "full_write")]
        #pragma warning disable CS1591
        Full_write,
        #pragma warning restore CS1591
        [EnumMember(Value = "comment_only")]
        #pragma warning disable CS1591
        Comment_only,
        #pragma warning restore CS1591
    }
}
