// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Panda.NuGet.AsanaClient.Clients.Exports.Graph;
using Panda.NuGet.AsanaClient.Clients.Exports.Resource;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Exports
{
    /// <summary>
    /// Builds and executes requests for operations under \exports
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExportsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The graph property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Exports.Graph.GraphRequestBuilder Graph
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Exports.Graph.GraphRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resource property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Exports.Resource.ResourceRequestBuilder Resource
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Exports.Resource.ResourceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Exports.ExportsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExportsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/exports", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Exports.ExportsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExportsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/exports", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
