// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Panda.NuGet.AsanaClient.Clients.Access_requests;
using Panda.NuGet.AsanaClient.Clients.Allocations;
using Panda.NuGet.AsanaClient.Clients.Attachments;
using Panda.NuGet.AsanaClient.Clients.Batch;
using Panda.NuGet.AsanaClient.Clients.Budgets;
using Panda.NuGet.AsanaClient.Clients.Custom_fields;
using Panda.NuGet.AsanaClient.Clients.Custom_types;
using Panda.NuGet.AsanaClient.Clients.Enum_options;
using Panda.NuGet.AsanaClient.Clients.Events;
using Panda.NuGet.AsanaClient.Clients.Exports;
using Panda.NuGet.AsanaClient.Clients.Goal_relationships;
using Panda.NuGet.AsanaClient.Clients.Goals;
using Panda.NuGet.AsanaClient.Clients.Jobs;
using Panda.NuGet.AsanaClient.Clients.Memberships;
using Panda.NuGet.AsanaClient.Clients.Organization_exports;
using Panda.NuGet.AsanaClient.Clients.Portfolio_memberships;
using Panda.NuGet.AsanaClient.Clients.Portfolios;
using Panda.NuGet.AsanaClient.Clients.Project_briefs;
using Panda.NuGet.AsanaClient.Clients.Project_memberships;
using Panda.NuGet.AsanaClient.Clients.Project_statuses;
using Panda.NuGet.AsanaClient.Clients.Project_templates;
using Panda.NuGet.AsanaClient.Clients.Projects;
using Panda.NuGet.AsanaClient.Clients.Rates;
using Panda.NuGet.AsanaClient.Clients.Reactions;
using Panda.NuGet.AsanaClient.Clients.Rule_triggers;
using Panda.NuGet.AsanaClient.Clients.Sections;
using Panda.NuGet.AsanaClient.Clients.Status_updates;
using Panda.NuGet.AsanaClient.Clients.Stories;
using Panda.NuGet.AsanaClient.Clients.Tags;
using Panda.NuGet.AsanaClient.Clients.Task_templates;
using Panda.NuGet.AsanaClient.Clients.Tasks;
using Panda.NuGet.AsanaClient.Clients.Team_memberships;
using Panda.NuGet.AsanaClient.Clients.Teams;
using Panda.NuGet.AsanaClient.Clients.Time_periods;
using Panda.NuGet.AsanaClient.Clients.Time_tracking_entries;
using Panda.NuGet.AsanaClient.Clients.User_task_lists;
using Panda.NuGet.AsanaClient.Clients.Users;
using Panda.NuGet.AsanaClient.Clients.Webhooks;
using Panda.NuGet.AsanaClient.Clients.Workspace_memberships;
using Panda.NuGet.AsanaClient.Clients.Workspaces;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Panda.NuGet.AsanaClient.Clients
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiClient : BaseRequestBuilder
    {
        /// <summary>The access_requests property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsRequestBuilder Access_requests
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The allocations property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsRequestBuilder Allocations
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The attachments property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Attachments.AttachmentsRequestBuilder Attachments
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Attachments.AttachmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The batch property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Batch.BatchRequestBuilder Batch
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Batch.BatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The budgets property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder Budgets
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The custom_fields property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsRequestBuilder Custom_fields
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The custom_types property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Custom_types.Custom_typesRequestBuilder Custom_types
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Custom_types.Custom_typesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enum_options property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Enum_options.Enum_optionsRequestBuilder Enum_options
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Enum_options.Enum_optionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Events.EventsRequestBuilder Events
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exports property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Exports.ExportsRequestBuilder Exports
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Exports.ExportsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The goal_relationships property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Goal_relationships.Goal_relationshipsRequestBuilder Goal_relationships
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Goal_relationships.Goal_relationshipsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The goals property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Goals.GoalsRequestBuilder Goals
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Goals.GoalsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jobs property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Jobs.JobsRequestBuilder Jobs
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Jobs.JobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The memberships property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Memberships.MembershipsRequestBuilder Memberships
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Memberships.MembershipsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organization_exports property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Organization_exports.Organization_exportsRequestBuilder Organization_exports
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Organization_exports.Organization_exportsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The portfolio_memberships property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsRequestBuilder Portfolio_memberships
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The portfolios property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Portfolios.PortfoliosRequestBuilder Portfolios
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Portfolios.PortfoliosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The project_briefs property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Project_briefs.Project_briefsRequestBuilder Project_briefs
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Project_briefs.Project_briefsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The project_memberships property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Project_memberships.Project_membershipsRequestBuilder Project_memberships
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Project_memberships.Project_membershipsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The project_statuses property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Project_statuses.Project_statusesRequestBuilder Project_statuses
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Project_statuses.Project_statusesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The project_templates property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Project_templates.Project_templatesRequestBuilder Project_templates
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Project_templates.Project_templatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projects property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder Projects
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rates property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Rates.RatesRequestBuilder Rates
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Rates.RatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reactions property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Reactions.ReactionsRequestBuilder Reactions
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Reactions.ReactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rule_triggers property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Rule_triggers.Rule_triggersRequestBuilder Rule_triggers
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Rule_triggers.Rule_triggersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sections property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Sections.SectionsRequestBuilder Sections
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Sections.SectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status_updates property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Status_updates.Status_updatesRequestBuilder Status_updates
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Status_updates.Status_updatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stories property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Stories.StoriesRequestBuilder Stories
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Stories.StoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Tags.TagsRequestBuilder Tags
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The task_templates property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Task_templates.Task_templatesRequestBuilder Task_templates
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Task_templates.Task_templatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tasks property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder Tasks
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Tasks.TasksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The team_memberships property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Team_memberships.Team_membershipsRequestBuilder Team_memberships
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Team_memberships.Team_membershipsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Teams.TeamsRequestBuilder Teams
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The time_periods property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Time_periods.Time_periodsRequestBuilder Time_periods
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Time_periods.Time_periodsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The time_tracking_entries property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Time_tracking_entries.Time_tracking_entriesRequestBuilder Time_tracking_entries
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Time_tracking_entries.Time_tracking_entriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user_task_lists property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.User_task_lists.User_task_listsRequestBuilder User_task_lists
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.User_task_lists.User_task_listsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Users.UsersRequestBuilder Users
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workspace_memberships property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Workspace_memberships.Workspace_membershipsRequestBuilder Workspace_memberships
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Workspace_memberships.Workspace_membershipsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workspaces property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Workspaces.WorkspacesRequestBuilder Workspaces
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Workspaces.WorkspacesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.ApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://app.asana.com/api/1.0";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
