// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies
{
    /// <summary>
    /// Builds and executes requests for operations under \tasks\{task_gid}\addDependencies
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AddDependenciesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AddDependenciesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tasks/{task_gid}/addDependencies{?opt_pretty*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AddDependenciesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tasks/{task_gid}/addDependencies{?opt_pretty*}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Marks a set of tasks as dependencies of this task, if they are not already dependencies. *A task can have at most 30 dependents and dependencies combined*.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesPostResponse?> PostAsAddDependenciesPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesRequestBuilder.AddDependenciesRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesPostResponse> PostAsAddDependenciesPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesRequestBuilder.AddDependenciesRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies401Error.CreateFromDiscriminatorValue },
                { "402", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies402Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesPostResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Marks a set of tasks as dependencies of this task, if they are not already dependencies. *A task can have at most 30 dependents and dependencies combined*.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsAddDependenciesPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesResponse?> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesRequestBuilder.AddDependenciesRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesResponse> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesRequestBuilder.AddDependenciesRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies401Error.CreateFromDiscriminatorValue },
                { "402", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies402Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependencies500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Marks a set of tasks as dependencies of this task, if they are not already dependencies. *A task can have at most 30 dependents and dependencies combined*.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesRequestBuilder.AddDependenciesRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesRequestBuilder.AddDependenciesRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Marks a set of tasks as dependencies of this task, if they are not already dependencies. *A task can have at most 30 dependents and dependencies combined*.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AddDependenciesRequestBuilderPostQueryParameters 
        {
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AddDependenciesRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.AddDependencies.AddDependenciesRequestBuilder.AddDependenciesRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
