// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Panda.NuGet.AsanaClient.Clients.Budgets.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Budgets
{
    /// <summary>
    /// Builds and executes requests for operations under \budgets
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BudgetsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Panda.NuGet.AsanaClient.Clients.budgets.item collection</summary>
        /// <param name="position">Globally unique identifier for the budget.</param>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder"/></returns>
        public global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("budget_gid", position);
                return new global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BudgetsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/budgets?parent={parent}{&opt_pretty*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BudgetsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/budgets?parent={parent}{&opt_pretty*}", rawUrl)
        {
        }
        /// <summary>
        /// Gets all budgets for a given *parent*. This will at most return a list of size 1 for a given *parent*.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsGetResponse?> GetAsBudgetsGetResponseAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder.BudgetsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsGetResponse> GetAsBudgetsGetResponseAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder.BudgetsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets401Error.CreateFromDiscriminatorValue },
                { "402", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets402Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsGetResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets all budgets for a given *parent*. This will at most return a list of size 1 for a given *parent*.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsBudgetsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsResponse?> GetAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder.BudgetsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsResponse> GetAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder.BudgetsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets401Error.CreateFromDiscriminatorValue },
                { "402", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets402Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new budget.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsPostResponse?> PostAsBudgetsPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder.BudgetsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsPostResponse> PostAsBudgetsPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder.BudgetsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets401Error.CreateFromDiscriminatorValue },
                { "402", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets402Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsPostResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new budget.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsBudgetsPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsResponse?> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder.BudgetsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsResponse> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder.BudgetsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets401Error.CreateFromDiscriminatorValue },
                { "402", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets402Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Budgets.Budgets500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets all budgets for a given *parent*. This will at most return a list of size 1 for a given *parent*.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder.BudgetsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder.BudgetsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new budget.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder.BudgetsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder.BudgetsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/budgets{?opt_pretty*}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets all budgets for a given *parent*. This will at most return a list of size 1 for a given *parent*.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BudgetsRequestBuilderGetQueryParameters 
        {
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
            /// <summary>Globally unique identifier for the budget&apos;s parent object. This currently can only be a `project`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("parent")]
            public string? Parent { get; set; }
#nullable restore
#else
            [QueryParameter("parent")]
            public string Parent { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BudgetsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder.BudgetsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Creates a new budget.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BudgetsRequestBuilderPostQueryParameters 
        {
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BudgetsRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.BudgetsRequestBuilder.BudgetsRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
