// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Budgets.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \budgets\{budget_gid}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithBudget_gItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithBudget_gItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/budgets/{budget_gid}{?opt_fields,opt_pretty*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithBudget_gItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/budgets/{budget_gid}{?opt_fields,opt_pretty*}", rawUrl)
        {
        }
        /// <summary>
        /// A specific, existing budget can be deleted by making a DELETE request on the URL for that budget.Returns an empty data record.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gDeleteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gDeleteResponse?> DeleteAsWithBudget_gDeleteResponseAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gDeleteResponse> DeleteAsWithBudget_gDeleteResponseAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g401Error.CreateFromDiscriminatorValue },
                { "402", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g402Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gDeleteResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gDeleteResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// A specific, existing budget can be deleted by making a DELETE request on the URL for that budget.Returns an empty data record.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use DeleteAsWithBudget_gDeleteResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gResponse?> DeleteAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gResponse> DeleteAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g401Error.CreateFromDiscriminatorValue },
                { "402", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g402Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the complete budget record for a single budget.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gGetResponse?> GetAsWithBudget_gGetResponseAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gGetResponse> GetAsWithBudget_gGetResponseAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g401Error.CreateFromDiscriminatorValue },
                { "402", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g402Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gGetResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the complete budget record for a single budget.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsWithBudget_gGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gResponse?> GetAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gResponse> GetAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g401Error.CreateFromDiscriminatorValue },
                { "402", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g402Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// An existing budget can be updated by making a PUT request on the URL forthat budget. Only the fields provided in the `data` block will be updated;any unspecified fields will remain unchanged.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gPutResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gPutResponse?> PutAsWithBudget_gPutResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gPutRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gPutResponse> PutAsWithBudget_gPutResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gPutRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g401Error.CreateFromDiscriminatorValue },
                { "402", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g402Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gPutResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gPutResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// An existing budget can be updated by making a PUT request on the URL forthat budget. Only the fields provided in the `data` block will be updated;any unspecified fields will remain unchanged.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g402Error">When receiving a 402 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PutAsWithBudget_gPutResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gResponse?> PutAsync(global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gPutRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gResponse> PutAsync(global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gPutRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g401Error.CreateFromDiscriminatorValue },
                { "402", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g402Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_g500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// A specific, existing budget can be deleted by making a DELETE request on the URL for that budget.Returns an empty data record.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns the complete budget record for a single budget.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// An existing budget can be updated by making a PUT request on the URL forthat budget. Only the fields provided in the `data` block will be updated;any unspecified fields will remain unchanged.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gPutRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gPutRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// A specific, existing budget can be deleted by making a DELETE request on the URL for that budget.Returns an empty data record.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithBudget_gItemRequestBuilderDeleteQueryParameters 
        {
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithBudget_gItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderDeleteQueryParameters>
        {
        }
        /// <summary>
        /// Returns the complete budget record for a single budget.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithBudget_gItemRequestBuilderGetQueryParameters 
        {
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
            [Obsolete("This property is deprecated, use OptFieldsAsGetOptFieldsQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public string[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public string[] OptFields { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.GetOpt_fieldsQueryParameterType[]? OptFieldsAsGetOptFieldsQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.GetOpt_fieldsQueryParameterType[] OptFieldsAsGetOptFieldsQueryParameterType { get; set; }
#endif
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithBudget_gItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// An existing budget can be updated by making a PUT request on the URL forthat budget. Only the fields provided in the `data` block will be updated;any unspecified fields will remain unchanged.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithBudget_gItemRequestBuilderPutQueryParameters 
        {
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
            [Obsolete("This property is deprecated, use OptFieldsAsPutOptFieldsQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public string[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public string[] OptFields { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.PutOpt_fieldsQueryParameterType[]? OptFieldsAsPutOptFieldsQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.PutOpt_fieldsQueryParameterType[] OptFieldsAsPutOptFieldsQueryParameterType { get; set; }
#endif
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithBudget_gItemRequestBuilderPutRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Budgets.Item.WithBudget_gItemRequestBuilder.WithBudget_gItemRequestBuilderPutQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
