// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Reactions
{
    /// <summary>
    /// An emoji reaction on an object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReactionsGetResponse_data : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The emoji string used in the reaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Emoji { get; set; }
#nullable restore
#else
        public string Emoji { get; set; }
#endif
        /// <summary>The ID of the reaction object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Gid { get; set; }
#nullable restore
#else
        public string Gid { get; set; }
#endif
        /// <summary>A *user* object represents an account in Asana that can be given access to various workspaces, projects, and tasks.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Panda.NuGet.AsanaClient.Clients.Reactions.ReactionsGetResponse_data_user? User { get; private set; }
#nullable restore
#else
        public global::Panda.NuGet.AsanaClient.Clients.Reactions.ReactionsGetResponse_data_user User { get; private set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Reactions.ReactionsGetResponse_data"/> and sets the default values.
        /// </summary>
        public ReactionsGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Reactions.ReactionsGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Panda.NuGet.AsanaClient.Clients.Reactions.ReactionsGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Panda.NuGet.AsanaClient.Clients.Reactions.ReactionsGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "emoji", n => { Emoji = n.GetStringValue(); } },
                { "gid", n => { Gid = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Panda.NuGet.AsanaClient.Clients.Reactions.ReactionsGetResponse_data_user>(global::Panda.NuGet.AsanaClient.Clients.Reactions.ReactionsGetResponse_data_user.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("emoji", Emoji);
            writer.WriteStringValue("gid", Gid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
