// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Access_requests
{
    /// <summary>
    /// A *access request* object represents a request to access a shareable resource within Asana. It includes the requester&apos;s information, approval status, and target resource details.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Access_requestsPostResponse_data : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The current approval status of the request.</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsPostResponse_data_approval_status? ApprovalStatus { get; set; }
        /// <summary>Globally unique identifier of the resource, as a string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Gid { get; private set; }
#nullable restore
#else
        public string Gid { get; private set; }
#endif
        /// <summary>The message included in the access request, if any.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The user who made the access request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsPostResponse_data_requester? Requester { get; private set; }
#nullable restore
#else
        public global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsPostResponse_data_requester Requester { get; private set; }
#endif
        /// <summary>The base type of this resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceType { get; private set; }
#nullable restore
#else
        public string ResourceType { get; private set; }
#endif
        /// <summary>The target resource that the requester wants access to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsPostResponse_data_target? Target { get; private set; }
#nullable restore
#else
        public global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsPostResponse_data_target Target { get; private set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsPostResponse_data"/> and sets the default values.
        /// </summary>
        public Access_requestsPostResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsPostResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsPostResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsPostResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "approval_status", n => { ApprovalStatus = n.GetEnumValue<global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsPostResponse_data_approval_status>(); } },
                { "gid", n => { Gid = n.GetStringValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "requester", n => { Requester = n.GetObjectValue<global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsPostResponse_data_requester>(global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsPostResponse_data_requester.CreateFromDiscriminatorValue); } },
                { "resource_type", n => { ResourceType = n.GetStringValue(); } },
                { "target", n => { Target = n.GetObjectValue<global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsPostResponse_data_target>(global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsPostResponse_data_target.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Panda.NuGet.AsanaClient.Clients.Access_requests.Access_requestsPostResponse_data_approval_status>("approval_status", ApprovalStatus);
            writer.WriteStringValue("message", Message);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
