// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Webhooks
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WebhooksPostRequestBody_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An array of WebhookFilter objects to specify a whitelist of filters to apply to events from this webhook. If a webhook event passes any of the filters the event will be delivered; otherwise no event will be sent to the receiving server.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Panda.NuGet.AsanaClient.Clients.Webhooks.WebhooksPostRequestBody_data_filters>? Filters { get; set; }
#nullable restore
#else
        public List<global::Panda.NuGet.AsanaClient.Clients.Webhooks.WebhooksPostRequestBody_data_filters> Filters { get; set; }
#endif
        /// <summary>A resource ID to subscribe to. Many Asana resources are valid to create webhooks on, but higher-level resources require filters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Resource { get; set; }
#nullable restore
#else
        public string Resource { get; set; }
#endif
        /// <summary>The URL to receive the HTTP POST. The full URL will be used to deliver events from this webhook (including parameters) which allows encoding of application-specific state when the webhook is created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Target { get; set; }
#nullable restore
#else
        public string Target { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Webhooks.WebhooksPostRequestBody_data"/> and sets the default values.
        /// </summary>
        public WebhooksPostRequestBody_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Webhooks.WebhooksPostRequestBody_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Panda.NuGet.AsanaClient.Clients.Webhooks.WebhooksPostRequestBody_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Panda.NuGet.AsanaClient.Clients.Webhooks.WebhooksPostRequestBody_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filters", n => { Filters = n.GetCollectionOfObjectValues<global::Panda.NuGet.AsanaClient.Clients.Webhooks.WebhooksPostRequestBody_data_filters>(global::Panda.NuGet.AsanaClient.Clients.Webhooks.WebhooksPostRequestBody_data_filters.CreateFromDiscriminatorValue)?.AsList(); } },
                { "resource", n => { Resource = n.GetStringValue(); } },
                { "target", n => { Target = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Panda.NuGet.AsanaClient.Clients.Webhooks.WebhooksPostRequestBody_data_filters>("filters", Filters);
            writer.WriteStringValue("resource", Resource);
            writer.WriteStringValue("target", Target);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
