// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Panda.NuGet.AsanaClient.Clients.Projects.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Projects
{
    /// <summary>
    /// Builds and executes requests for operations under \projects
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Panda.NuGet.AsanaClient.Clients.projects.item collection</summary>
        /// <param name="position">Globally unique identifier for the project.</param>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Item.WithProject_gItemRequestBuilder"/></returns>
        public global::Panda.NuGet.AsanaClient.Clients.Projects.Item.WithProject_gItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("project_gid", position);
                return new global::Panda.NuGet.AsanaClient.Clients.Projects.Item.WithProject_gItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects{?archived*,limit*,offset*,opt_fields,opt_pretty*,team*,workspace*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects{?archived*,limit*,offset*,opt_fields,opt_pretty*,team*,workspace*}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;projects:read&lt;/code&gt;Returns the compact project records for some filtered set of projects. Use one or more of the parameters provided to filter the projects returned.*Note: This endpoint may timeout for large domains. Try filtering by team!*
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsGetResponse?> GetAsProjectsGetResponseAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsGetResponse> GetAsProjectsGetResponseAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsGetResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;projects:read&lt;/code&gt;Returns the compact project records for some filtered set of projects. Use one or more of the parameters provided to filter the projects returned.*Note: This endpoint may timeout for large domains. Try filtering by team!*
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsProjectsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsResponse?> GetAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsResponse> GetAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;projects:write&lt;/code&gt;Create a new project in a workspace or team.Every project is required to be created in a specific workspace ororganization, and this cannot be changed once set. Note that you can usethe `workspace` parameter regardless of whether or not it is anorganization.If the workspace for your project is an organization, you must alsosupply a `team` to share the project with.Returns the full record of the newly created project.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsPostResponse?> PostAsProjectsPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsPostResponse> PostAsProjectsPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsPostResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;projects:write&lt;/code&gt;Create a new project in a workspace or team.Every project is required to be created in a specific workspace ororganization, and this cannot be changed once set. Note that you can usethe `workspace` parameter regardless of whether or not it is anorganization.If the workspace for your project is an organization, you must alsosupply a `team` to share the project with.Returns the full record of the newly created project.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Projects.Projects500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsProjectsPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsResponse?> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsResponse> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Projects.Projects500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;projects:read&lt;/code&gt;Returns the compact project records for some filtered set of projects. Use one or more of the parameters provided to filter the projects returned.*Note: This endpoint may timeout for large domains. Try filtering by team!*
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;projects:write&lt;/code&gt;Create a new project in a workspace or team.Every project is required to be created in a specific workspace ororganization, and this cannot be changed once set. Note that you can usethe `workspace` parameter regardless of whether or not it is anorganization.If the workspace for your project is an organization, you must alsosupply a `team` to share the project with.Returns the full record of the newly created project.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;projects:read&lt;/code&gt;Returns the compact project records for some filtered set of projects. Use one or more of the parameters provided to filter the projects returned.*Note: This endpoint may timeout for large domains. Try filtering by team!*
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProjectsRequestBuilderGetQueryParameters 
        {
            /// <summary>Only return projects whose `archived` field takes on the value of this parameter.</summary>
            [QueryParameter("archived")]
            public bool? Archived { get; set; }
            /// <summary>Results per page.The number of objects to return per page. The value must be between 1 and 100.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Offset token.An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results.*Note: You can only pass in an offset that was returned to you via a previously paginated request.*</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("offset")]
            public string? Offset { get; set; }
#nullable restore
#else
            [QueryParameter("offset")]
            public string Offset { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
            [Obsolete("This property is deprecated, use OptFieldsAsGetOptFieldsQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public string[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public string[] OptFields { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Projects.GetOpt_fieldsQueryParameterType[]? OptFieldsAsGetOptFieldsQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Projects.GetOpt_fieldsQueryParameterType[] OptFieldsAsGetOptFieldsQueryParameterType { get; set; }
#endif
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
            /// <summary>The team to filter projects on.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("team")]
            public string? Team { get; set; }
#nullable restore
#else
            [QueryParameter("team")]
            public string Team { get; set; }
#endif
            /// <summary>The workspace or organization to filter projects on.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("workspace")]
            public string? Workspace { get; set; }
#nullable restore
#else
            [QueryParameter("workspace")]
            public string Workspace { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProjectsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;projects:write&lt;/code&gt;Create a new project in a workspace or team.Every project is required to be created in a specific workspace ororganization, and this cannot be changed once set. Note that you can usethe `workspace` parameter regardless of whether or not it is anorganization.If the workspace for your project is an organization, you must alsosupply a `team` to share the project with.Returns the full record of the newly created project.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProjectsRequestBuilderPostQueryParameters 
        {
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
            [Obsolete("This property is deprecated, use OptFieldsAsPostOptFieldsQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public string[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public string[] OptFields { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Projects.PostOpt_fieldsQueryParameterType[]? OptFieldsAsPostOptFieldsQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Projects.PostOpt_fieldsQueryParameterType[] OptFieldsAsPostOptFieldsQueryParameterType { get; set; }
#endif
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProjectsRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Projects.ProjectsRequestBuilder.ProjectsRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
