// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag
{
    /// <summary>
    /// Builds and executes requests for operations under \tasks\{task_gid}\removeTag
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RemoveTagRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RemoveTagRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tasks/{task_gid}/removeTag{?opt_pretty*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RemoveTagRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tasks/{task_gid}/removeTag{?opt_pretty*}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Removes a tag from a task. Returns an empty data block.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagPostResponse?> PostAsRemoveTagPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagRequestBuilder.RemoveTagRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagPostResponse> PostAsRemoveTagPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagRequestBuilder.RemoveTagRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagPostResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Removes a tag from a task. Returns an empty data block.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsRemoveTagPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagResponse?> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagRequestBuilder.RemoveTagRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagResponse> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagRequestBuilder.RemoveTagRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTag500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Removes a tag from a task. Returns an empty data block.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagRequestBuilder.RemoveTagRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagRequestBuilder.RemoveTagRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;tasks:write&lt;/code&gt;Removes a tag from a task. Returns an empty data block.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RemoveTagRequestBuilderPostQueryParameters 
        {
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RemoveTagRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Tasks.Item.RemoveTag.RemoveTagRequestBuilder.RemoveTagRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
