// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert
{
    /// <summary>
    /// Builds and executes requests for operations under \custom_fields\{custom_field_gid}\enum_options\insert
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InsertRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InsertRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/custom_fields/{custom_field_gid}/enum_options/insert{?opt_fields,opt_pretty*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InsertRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/custom_fields/{custom_field_gid}/enum_options/insert{?opt_fields,opt_pretty*}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;custom_fields:write&lt;/code&gt;Moves a particular enum option to be either before or after another specified enum option in the custom field.Locked custom fields can only be reordered by the user who locked the field.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertPostResponse?> PostAsInsertPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertRequestBuilder.InsertRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertPostResponse> PostAsInsertPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertRequestBuilder.InsertRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertPostResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;custom_fields:write&lt;/code&gt;Moves a particular enum option to be either before or after another specified enum option in the custom field.Locked custom fields can only be reordered by the user who locked the field.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsInsertPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertResponse?> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertRequestBuilder.InsertRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertResponse> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertRequestBuilder.InsertRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.Insert500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;custom_fields:write&lt;/code&gt;Moves a particular enum option to be either before or after another specified enum option in the custom field.Locked custom fields can only be reordered by the user who locked the field.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertRequestBuilder.InsertRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertRequestBuilder.InsertRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;custom_fields:write&lt;/code&gt;Moves a particular enum option to be either before or after another specified enum option in the custom field.Locked custom fields can only be reordered by the user who locked the field.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InsertRequestBuilderPostQueryParameters 
        {
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
            [Obsolete("This property is deprecated, use OptFieldsAsPostOptFieldsQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public string[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public string[] OptFields { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.PostOpt_fieldsQueryParameterType[]? OptFieldsAsPostOptFieldsQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.PostOpt_fieldsQueryParameterType[] OptFieldsAsPostOptFieldsQueryParameterType { get; set; }
#endif
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InsertRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.Enum_options.Insert.InsertRequestBuilder.InsertRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
