// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Panda.NuGet.AsanaClient.Clients.Workspaces.Item.AddUser;
using Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Audit_log_events;
using Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Custom_fields;
using Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Events;
using Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Projects;
using Panda.NuGet.AsanaClient.Clients.Workspaces.Item.RemoveUser;
using Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags;
using Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tasks;
using Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Teams;
using Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Typeahead;
using Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Users;
using Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Workspace_memberships;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Workspaces.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \workspaces\{workspace_gid}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithWorkspace_gItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The addUser property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.AddUser.AddUserRequestBuilder AddUser
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.AddUser.AddUserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The audit_log_events property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Audit_log_events.Audit_log_eventsRequestBuilder Audit_log_events
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Audit_log_events.Audit_log_eventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The custom_fields property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Custom_fields.Custom_fieldsRequestBuilder Custom_fields
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Custom_fields.Custom_fieldsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Events.EventsRequestBuilder Events
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projects property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Projects.ProjectsRequestBuilder Projects
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Projects.ProjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The removeUser property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.RemoveUser.RemoveUserRequestBuilder RemoveUser
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.RemoveUser.RemoveUserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder Tags
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tasks property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tasks.TasksRequestBuilder Tasks
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Tasks.TasksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Teams.TeamsRequestBuilder Teams
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The typeahead property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Typeahead.TypeaheadRequestBuilder Typeahead
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Typeahead.TypeaheadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Users.UsersRequestBuilder Users
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workspace_memberships property</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Workspace_memberships.Workspace_membershipsRequestBuilder Workspace_memberships
        {
            get => new global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.Workspace_memberships.Workspace_membershipsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWorkspace_gItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workspaces/{workspace_gid}{?opt_fields,opt_pretty*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWorkspace_gItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workspaces/{workspace_gid}{?opt_fields,opt_pretty*}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;workspaces:read&lt;/code&gt;Returns the full workspace record for a single workspace.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gGetResponse?> GetAsWithWorkspace_gGetResponseAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder.WithWorkspace_gItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gGetResponse> GetAsWithWorkspace_gGetResponseAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder.WithWorkspace_gItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gGetResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;workspaces:read&lt;/code&gt;Returns the full workspace record for a single workspace.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsWithWorkspace_gGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gResponse?> GetAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder.WithWorkspace_gItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gResponse> GetAsync(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder.WithWorkspace_gItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// A specific, existing workspace can be updated by making a PUT request on the URL for that workspace. Only the fields provided in the data block will be updated; any unspecified fields will remain unchanged.Currently the only field that can be modified for a workspace is its name.Returns the complete, updated workspace record.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gPutResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gPutResponse?> PutAsWithWorkspace_gPutResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gPutRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder.WithWorkspace_gItemRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gPutResponse> PutAsWithWorkspace_gPutResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gPutRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder.WithWorkspace_gItemRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gPutResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gPutResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// A specific, existing workspace can be updated by making a PUT request on the URL for that workspace. Only the fields provided in the data block will be updated; any unspecified fields will remain unchanged.Currently the only field that can be modified for a workspace is its name.Returns the complete, updated workspace record.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PutAsWithWorkspace_gPutResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gResponse?> PutAsync(global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gPutRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder.WithWorkspace_gItemRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gResponse> PutAsync(global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gPutRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder.WithWorkspace_gItemRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_g500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;workspaces:read&lt;/code&gt;Returns the full workspace record for a single workspace.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder.WithWorkspace_gItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder.WithWorkspace_gItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// A specific, existing workspace can be updated by making a PUT request on the URL for that workspace. Only the fields provided in the data block will be updated; any unspecified fields will remain unchanged.Currently the only field that can be modified for a workspace is its name.Returns the complete, updated workspace record.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gPutRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder.WithWorkspace_gItemRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gPutRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder.WithWorkspace_gItemRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;workspaces:read&lt;/code&gt;Returns the full workspace record for a single workspace.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithWorkspace_gItemRequestBuilderGetQueryParameters 
        {
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
            [Obsolete("This property is deprecated, use OptFieldsAsGetOptFieldsQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public string[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public string[] OptFields { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.GetOpt_fieldsQueryParameterType[]? OptFieldsAsGetOptFieldsQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.GetOpt_fieldsQueryParameterType[] OptFieldsAsGetOptFieldsQueryParameterType { get; set; }
#endif
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithWorkspace_gItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder.WithWorkspace_gItemRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// A specific, existing workspace can be updated by making a PUT request on the URL for that workspace. Only the fields provided in the data block will be updated; any unspecified fields will remain unchanged.Currently the only field that can be modified for a workspace is its name.Returns the complete, updated workspace record.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithWorkspace_gItemRequestBuilderPutQueryParameters 
        {
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
            [Obsolete("This property is deprecated, use OptFieldsAsPutOptFieldsQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public string[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public string[] OptFields { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.PutOpt_fieldsQueryParameterType[]? OptFieldsAsPutOptFieldsQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.PutOpt_fieldsQueryParameterType[] OptFieldsAsPutOptFieldsQueryParameterType { get; set; }
#endif
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithWorkspace_gItemRequestBuilderPutRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Workspaces.Item.WithWorkspace_gItemRequestBuilder.WithWorkspace_gItemRequestBuilderPutQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
