// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Teams.Item
{
    /// <summary>Controls who can create and share content with the team</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithTeam_gPutResponse_data_team_content_management_access_level
    {
        [EnumMember(Value = "no_restriction")]
        #pragma warning disable CS1591
        No_restriction,
        #pragma warning restore CS1591
        [EnumMember(Value = "only_team_admins")]
        #pragma warning disable CS1591
        Only_team_admins,
        #pragma warning restore CS1591
    }
}
