// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Panda.NuGet.AsanaClient.Clients.Custom_fields.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Custom_fields
{
    /// <summary>
    /// Builds and executes requests for operations under \custom_fields
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Custom_fieldsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Panda.NuGet.AsanaClient.Clients.custom_fields.item collection</summary>
        /// <param name="position">Globally unique identifier for the custom field.</param>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.WithCustom_field_gItemRequestBuilder"/></returns>
        public global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.WithCustom_field_gItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("custom_field_gid", position);
                return new global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Item.WithCustom_field_gItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Custom_fieldsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/custom_fields{?opt_fields,opt_pretty*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Custom_fieldsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/custom_fields{?opt_fields,opt_pretty*}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;custom_fields:write&lt;/code&gt;Creates a new custom field in a workspace. Every custom field is requiredto be created in a specific workspace, and this workspace cannot bechanged once set.A custom field’s name must be unique within a workspace and not conflictwith names of existing task properties such as `Due Date` or `Assignee`.A custom field’s type must be one of `text`, `enum`, `multi_enum`, `number`,`date`, or `people`.Returns the full record of the newly created custom field.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsPostResponse?> PostAsCustom_fieldsPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsRequestBuilder.Custom_fieldsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsPostResponse> PostAsCustom_fieldsPostResponseAsync(global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsRequestBuilder.Custom_fieldsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsPostResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;custom_fields:write&lt;/code&gt;Creates a new custom field in a workspace. Every custom field is requiredto be created in a specific workspace, and this workspace cannot bechanged once set.A custom field’s name must be unique within a workspace and not conflictwith names of existing task properties such as `Due Date` or `Assignee`.A custom field’s type must be one of `text`, `enum`, `multi_enum`, `number`,`date`, or `people`.Returns the full record of the newly created custom field.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsCustom_fieldsPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsResponse?> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsRequestBuilder.Custom_fieldsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsResponse> PostAsync(global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsRequestBuilder.Custom_fieldsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields400Error.CreateFromDiscriminatorValue },
                { "401", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields401Error.CreateFromDiscriminatorValue },
                { "403", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields403Error.CreateFromDiscriminatorValue },
                { "404", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields404Error.CreateFromDiscriminatorValue },
                { "500", global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fields500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsResponse>(requestInfo, global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;custom_fields:write&lt;/code&gt;Creates a new custom field in a workspace. Every custom field is requiredto be created in a specific workspace, and this workspace cannot bechanged once set.A custom field’s name must be unique within a workspace and not conflictwith names of existing task properties such as `Due Date` or `Assignee`.A custom field’s type must be one of `text`, `enum`, `multi_enum`, `number`,`date`, or `people`.Returns the full record of the newly created custom field.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsRequestBuilder.Custom_fieldsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsPostRequestBody body, Action<RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsRequestBuilder.Custom_fieldsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &lt;b&gt;Required scope: &lt;/b&gt;&lt;code&gt;custom_fields:write&lt;/code&gt;Creates a new custom field in a workspace. Every custom field is requiredto be created in a specific workspace, and this workspace cannot bechanged once set.A custom field’s name must be unique within a workspace and not conflictwith names of existing task properties such as `Due Date` or `Assignee`.A custom field’s type must be one of `text`, `enum`, `multi_enum`, `number`,`date`, or `people`.Returns the full record of the newly created custom field.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Custom_fieldsRequestBuilderPostQueryParameters 
        {
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
            [Obsolete("This property is deprecated, use OptFieldsAsPostOptFieldsQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public string[]? OptFields { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public string[] OptFields { get; set; }
#endif
            /// <summary>This endpoint returns a resource which excludes some properties by default. To include those optional properties, set this query parameter to a comma-separated list of the properties you wish to include.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Custom_fields.PostOpt_fieldsQueryParameterType[]? OptFieldsAsPostOptFieldsQueryParameterType { get; set; }
#nullable restore
#else
            [QueryParameter("opt_fields")]
            public global::Panda.NuGet.AsanaClient.Clients.Custom_fields.PostOpt_fieldsQueryParameterType[] OptFieldsAsPostOptFieldsQueryParameterType { get; set; }
#endif
            /// <summary>Provides “pretty” output.Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.</summary>
            [QueryParameter("opt_pretty")]
            public bool? OptPretty { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Custom_fieldsRequestBuilderPostRequestConfiguration : RequestConfiguration<global::Panda.NuGet.AsanaClient.Clients.Custom_fields.Custom_fieldsRequestBuilder.Custom_fieldsRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
