// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Teams.Item.Projects
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProjectsPostRequestBody_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An object where each key is the GID of a custom field and its corresponding value is either an enum GID, string, number, or object (depending on the custom field type). See the [custom fields guide](/docs/custom-fields-guide) for details on creating and updating custom field values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Panda.NuGet.AsanaClient.Clients.Teams.Item.Projects.ProjectsPostRequestBody_data_custom_fields? CustomFields { get; set; }
#nullable restore
#else
        public global::Panda.NuGet.AsanaClient.Clients.Teams.Item.Projects.ProjectsPostRequestBody_data_custom_fields CustomFields { get; set; }
#endif
        /// <summary>*Create-only*. Comma separated string of users. Followers are a subset of members who have opted in to receive &quot;tasks added&quot; notifications for a project.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Followers { get; set; }
#nullable restore
#else
        public string Followers { get; set; }
#endif
        /// <summary>The current owner of the project, may be null.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Owner { get; set; }
#nullable restore
#else
        public string Owner { get; set; }
#endif
        /// <summary>The team that this project is shared with.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Team { get; set; }
#nullable restore
#else
        public string Team { get; set; }
#endif
        /// <summary>The `gid` of a workspace.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Workspace { get; set; }
#nullable restore
#else
        public string Workspace { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Teams.Item.Projects.ProjectsPostRequestBody_data"/> and sets the default values.
        /// </summary>
        public ProjectsPostRequestBody_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Teams.Item.Projects.ProjectsPostRequestBody_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Panda.NuGet.AsanaClient.Clients.Teams.Item.Projects.ProjectsPostRequestBody_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Panda.NuGet.AsanaClient.Clients.Teams.Item.Projects.ProjectsPostRequestBody_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "custom_fields", n => { CustomFields = n.GetObjectValue<global::Panda.NuGet.AsanaClient.Clients.Teams.Item.Projects.ProjectsPostRequestBody_data_custom_fields>(global::Panda.NuGet.AsanaClient.Clients.Teams.Item.Projects.ProjectsPostRequestBody_data_custom_fields.CreateFromDiscriminatorValue); } },
                { "followers", n => { Followers = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetStringValue(); } },
                { "team", n => { Team = n.GetStringValue(); } },
                { "workspace", n => { Workspace = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Panda.NuGet.AsanaClient.Clients.Teams.Item.Projects.ProjectsPostRequestBody_data_custom_fields>("custom_fields", CustomFields);
            writer.WriteStringValue("followers", Followers);
            writer.WriteStringValue("owner", Owner);
            writer.WriteStringValue("team", Team);
            writer.WriteStringValue("workspace", Workspace);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
