// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Portfolio_memberships
{
    /// <summary>
    /// This object determines if a user is a member of a portfolio.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Portfolio_membershipsGetResponse_data : IAdditionalDataHolder, IParsable
    {
        /// <summary>Whether the member has admin, editor, or viewer access to the portfolio. Portfolios do not support commenter access yet.</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsGetResponse_data_access_level? AccessLevel { get; private set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Globally unique identifier of the resource, as a string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Gid { get; private set; }
#nullable restore
#else
        public string Gid { get; private set; }
#endif
        /// <summary>[Opt In](/docs/inputoutput-options). The portfolio the user is a member of.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsGetResponse_data_portfolio? Portfolio { get; set; }
#nullable restore
#else
        public global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsGetResponse_data_portfolio Portfolio { get; set; }
#endif
        /// <summary>The base type of this resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceType { get; private set; }
#nullable restore
#else
        public string ResourceType { get; private set; }
#endif
        /// <summary>A *user* object represents an account in Asana that can be given access to various workspaces, projects, and tasks.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsGetResponse_data_user? User { get; set; }
#nullable restore
#else
        public global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsGetResponse_data_user User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsGetResponse_data"/> and sets the default values.
        /// </summary>
        public Portfolio_membershipsGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_level", n => { AccessLevel = n.GetEnumValue<global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsGetResponse_data_access_level>(); } },
                { "gid", n => { Gid = n.GetStringValue(); } },
                { "portfolio", n => { Portfolio = n.GetObjectValue<global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsGetResponse_data_portfolio>(global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsGetResponse_data_portfolio.CreateFromDiscriminatorValue); } },
                { "resource_type", n => { ResourceType = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsGetResponse_data_user>(global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsGetResponse_data_user.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsGetResponse_data_portfolio>("portfolio", Portfolio);
            writer.WriteObjectValue<global::Panda.NuGet.AsanaClient.Clients.Portfolio_memberships.Portfolio_membershipsGetResponse_data_user>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
