// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Allocations
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AllocationsPostResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assignee property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_assignee? Assignee { get; set; }
#nullable restore
#else
        public global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_assignee Assignee { get; set; }
#endif
        /// <summary>The user who created the allocation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_created_by? CreatedBy { get; set; }
#nullable restore
#else
        public global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_created_by CreatedBy { get; set; }
#endif
        /// <summary>The amount of time associated with the allocation, represented as a percentage or number of hours.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_effort? Effort { get; set; }
#nullable restore
#else
        public global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_effort Effort { get; set; }
#endif
        /// <summary>The localized day on which the allocation ends.</summary>
        public Date? EndDate { get; set; }
        /// <summary>Globally unique identifier of the resource, as a string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Gid { get; private set; }
#nullable restore
#else
        public string Gid { get; private set; }
#endif
        /// <summary>The project the allocation is on.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_parent? Parent { get; set; }
#nullable restore
#else
        public global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_parent Parent { get; set; }
#endif
        /// <summary>The subtype of the allocation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceSubtype { get; set; }
#nullable restore
#else
        public string ResourceSubtype { get; set; }
#endif
        /// <summary>The base type of this resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceType { get; private set; }
#nullable restore
#else
        public string ResourceType { get; private set; }
#endif
        /// <summary>The localized day on which the allocation starts.</summary>
        public Date? StartDate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data"/> and sets the default values.
        /// </summary>
        public AllocationsPostResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignee", n => { Assignee = n.GetObjectValue<global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_assignee>(global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_assignee.CreateFromDiscriminatorValue); } },
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_created_by>(global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_created_by.CreateFromDiscriminatorValue); } },
                { "effort", n => { Effort = n.GetObjectValue<global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_effort>(global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_effort.CreateFromDiscriminatorValue); } },
                { "end_date", n => { EndDate = n.GetDateValue(); } },
                { "gid", n => { Gid = n.GetStringValue(); } },
                { "parent", n => { Parent = n.GetObjectValue<global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_parent>(global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_parent.CreateFromDiscriminatorValue); } },
                { "resource_subtype", n => { ResourceSubtype = n.GetStringValue(); } },
                { "resource_type", n => { ResourceType = n.GetStringValue(); } },
                { "start_date", n => { StartDate = n.GetDateValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_assignee>("assignee", Assignee);
            writer.WriteObjectValue<global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_created_by>("created_by", CreatedBy);
            writer.WriteObjectValue<global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_effort>("effort", Effort);
            writer.WriteDateValue("end_date", EndDate);
            writer.WriteObjectValue<global::Panda.NuGet.AsanaClient.Clients.Allocations.AllocationsPostResponse_data_parent>("parent", Parent);
            writer.WriteStringValue("resource_subtype", ResourceSubtype);
            writer.WriteDateValue("start_date", StartDate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
