// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Panda.NuGet.AsanaClient.Clients.Task_templates.Item.InstantiateTask
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InstantiateTaskPostResponse_data_new_task : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>[Opt In](/docs/inputoutput-options). A *user* object represents an account in Asana that can be given access to various workspaces, projects, and tasks.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Panda.NuGet.AsanaClient.Clients.Task_templates.Item.InstantiateTask.InstantiateTaskPostResponse_data_new_task_created_by? CreatedBy { get; private set; }
#nullable restore
#else
        public global::Panda.NuGet.AsanaClient.Clients.Task_templates.Item.InstantiateTask.InstantiateTaskPostResponse_data_new_task_created_by CreatedBy { get; private set; }
#endif
        /// <summary>Globally unique identifier of the resource, as a string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Gid { get; private set; }
#nullable restore
#else
        public string Gid { get; private set; }
#endif
        /// <summary>The name of the task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The subtype of this resource. Different subtypes retain many of the same fields and behavior, but may render differently in Asana or represent resources with different semantic meaning.The resource_subtype `milestone` represent a single moment in time. This means tasks with this subtype cannot have a start_date.</summary>
        public global::Panda.NuGet.AsanaClient.Clients.Task_templates.Item.InstantiateTask.InstantiateTaskPostResponse_data_new_task_resource_subtype? ResourceSubtype { get; set; }
        /// <summary>The base type of this resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResourceType { get; private set; }
#nullable restore
#else
        public string ResourceType { get; private set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Panda.NuGet.AsanaClient.Clients.Task_templates.Item.InstantiateTask.InstantiateTaskPostResponse_data_new_task"/> and sets the default values.
        /// </summary>
        public InstantiateTaskPostResponse_data_new_task()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Panda.NuGet.AsanaClient.Clients.Task_templates.Item.InstantiateTask.InstantiateTaskPostResponse_data_new_task"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Panda.NuGet.AsanaClient.Clients.Task_templates.Item.InstantiateTask.InstantiateTaskPostResponse_data_new_task CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Panda.NuGet.AsanaClient.Clients.Task_templates.Item.InstantiateTask.InstantiateTaskPostResponse_data_new_task();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_by", n => { CreatedBy = n.GetObjectValue<global::Panda.NuGet.AsanaClient.Clients.Task_templates.Item.InstantiateTask.InstantiateTaskPostResponse_data_new_task_created_by>(global::Panda.NuGet.AsanaClient.Clients.Task_templates.Item.InstantiateTask.InstantiateTaskPostResponse_data_new_task_created_by.CreateFromDiscriminatorValue); } },
                { "gid", n => { Gid = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "resource_subtype", n => { ResourceSubtype = n.GetEnumValue<global::Panda.NuGet.AsanaClient.Clients.Task_templates.Item.InstantiateTask.InstantiateTaskPostResponse_data_new_task_resource_subtype>(); } },
                { "resource_type", n => { ResourceType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Panda.NuGet.AsanaClient.Clients.Task_templates.Item.InstantiateTask.InstantiateTaskPostResponse_data_new_task_resource_subtype>("resource_subtype", ResourceSubtype);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
